package corbaBanque;

/**
* corbaBanque/BanqueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Monday, November 3, 2025 10:15:20 PM CET
*/

public final class BanqueHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaBanque.Banque value = null;

  public BanqueHolder ()
  {
  }

  public BanqueHolder (corbaBanque.Banque initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaBanque.BanqueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaBanque.BanqueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaBanque.BanqueHelper.type ();
  }

}
