package corbaBanque;


/**
* corbaBanque/Banque.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Monday, November 3, 2025 10:15:20 PM CET
*/

public interface Banque extends BanqueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Banque
