package corbaBanque;


/**
* corbaBanque/BanqueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Monday, November 10, 2025 10:27:41 PM CET
*/

public interface BanqueOperations 
{
  void creerCompte (corbaBanque.Compte cpte);
  void verser (float mt, int code);
  void retirer (float mt, int code);
  corbaBanque.Compte getCompte (int code);
  corbaBanque.Compte[] getComptes ();
  double conversion (float mt);
} // interface BanqueOperations
